//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIOracleTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELF_COMPANYINFO
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string TEL { get; set; }
        public string ORGCODE { get; set; }
        public string OWNER { get; set; }
        public string GSSH { get; set; }
        public string DSSH { get; set; }
        public string REGSN { get; set; }
        public string MISC { get; set; }
    }
}
