//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIOracleTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELF_USRS
    {
        public long ID { get; set; }
        public string UNAME { get; set; }
        public string PSWD { get; set; }
        public string STATUS { get; set; }
        public string AFTERCERSN { get; set; }
        public string BEFORCERSN { get; set; }
        public string NOWCERSN { get; set; }
        public string UNUSED01 { get; set; }
        public string UNUSED02 { get; set; }
        public string UNUSED03 { get; set; }
        public string PHNO { get; set; }
        public string UEMAIL { get; set; }
        public string MPHNO { get; set; }
        public string SENDADDS { get; set; }
        public string USERID { get; set; }
        public string SENDNAME { get; set; }
        public string SENDNO { get; set; }
        public string SENDCODE { get; set; }
        public string DOWNCODE { get; set; }
    }
}
