//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIOracleTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCERTTASK
    {
        public long ID { get; set; }
        public string CANO { get; set; }
        public Nullable<long> RECORDID { get; set; }
        public Nullable<long> TBCERTID { get; set; }
        public Nullable<long> TBCERTTYPEID { get; set; }
        public Nullable<long> ITEMID { get; set; }
        public Nullable<long> TBTYPEINFO { get; set; }
        public Nullable<long> STATUSID { get; set; }
        public Nullable<long> PAYSTATUSID { get; set; }
        public Nullable<long> ESTATUSID { get; set; }
        public string HANDLENAME { get; set; }
        public string HANDLEPHONE { get; set; }
        public string HANDLEID { get; set; }
        public string ISKEY { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<decimal> APPLYID { get; set; }
        public Nullable<System.DateTime> APPLYDATE { get; set; }
        public Nullable<decimal> DEALNAME { get; set; }
        public Nullable<System.DateTime> DEALDATE { get; set; }
        public string SN { get; set; }
        public string CERTTASKSIGN { get; set; }
        public string PUBLICKEY { get; set; }
        public string TASKCONTENT { get; set; }
        public string REMARK { get; set; }
        public string APPLYTYPE { get; set; }
        public string AUTHORIZATIONCODE { get; set; }
        public Nullable<System.DateTime> VERIFYDATE { get; set; }
        public Nullable<System.DateTime> FINISHDATE { get; set; }
        public string REQSN { get; set; }
        public string ISRECEIPT { get; set; }
        public string DISTRIBUTIONMESSAGE { get; set; }
        public Nullable<long> KEYTYPE { get; set; }
        public string JINSUITYPE { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<System.DateTime> RECEIVEDATE { get; set; }
        public string ISBACK { get; set; }
        public string BACKCANO { get; set; }
    }
}
