//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIOracleTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCERT
    {
        public long ID { get; set; }
        public Nullable<long> RECORDID { get; set; }
        public string CN { get; set; }
        public string DN { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public string CERTTYPE { get; set; }
        public string KEYTYPE { get; set; }
        public string STATUS { get; set; }
        public string CERTREF { get; set; }
        public Nullable<long> INVALID { get; set; }
        public string PUBLICKEY { get; set; }
        public Nullable<long> TBCERTTYPEID { get; set; }
        public Nullable<long> ITEMID { get; set; }
        public string ENCSN { get; set; }
        public string SIGNSN { get; set; }
        public string AUTHORIZECODE { get; set; }
        public string KEYID { get; set; }
        public Nullable<long> QUALITYSTATUS { get; set; }
        public string CTMLNAME { get; set; }
        public string LASTCERTSN { get; set; }
        public string ADMINCERTDN { get; set; }
        public string ADMINCERTSN { get; set; }
    }
}
