//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIOracleTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBITEM
    {
        public long ITEMID { get; set; }
        public string ITEM { get; set; }
        public long FREEPERIOD { get; set; }
        public long ISLIMIT { get; set; }
        public long COUNT { get; set; }
        public long USECOUNT { get; set; }
        public long ITEMLEVEL { get; set; }
        public string ITEMCLIENT { get; set; }
        public string ITEMDEVELOPERS { get; set; }
        public Nullable<long> TEMPLATEID { get; set; }
        public string REMARK { get; set; }
        public string ITEMCODE { get; set; }
        public long TBITEMTYPEID { get; set; }
    }
}
