//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIOracleTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUSERINFO
    {
        public long ID { get; set; }
        public string USERCODE { get; set; }
        public string USERNAME { get; set; }
        public string AREACODE { get; set; }
        public long ISSTAFF { get; set; }
        public Nullable<long> AGENCYID { get; set; }
        public string CERTSN { get; set; }
        public string IDCARD { get; set; }
        public string PHONE { get; set; }
    }
}
